import logging
import decimal
from collections import defaultdict
from typing import List, Dict, Any, Optional, Tuple
from ..util.converters import DataConverter

_convert_to_decimal = DataConverter.convert_to_decimal


def _int_sum_reducer(values: List[Any]) -> int:
    """Sums integer-like values. Strips commas before conversion."""
    total = 0
    for val in values:
        if val is not None:
            try:
                total += int(float(str(val).replace(',', '')))
            except (ValueError, TypeError):
                pass
    return total

class Aggregator:
    """
    Generic, declarative data aggregator that groups rows by a key generated by
    key_selector and applies column-specific reduction strategies.
    """
    def __init__(self, key_selector, reducers):
        self.key_selector = key_selector
        self.reducers = reducers

    def aggregate(self, rows: List[Dict[str, Any]], target_map: Dict[Tuple, Dict[str, Any]] = None) -> Dict[Tuple, Dict[str, Any]]:
        """
        Reduce rows into target_map.

        Each entry in self.reducers must be a (in_col: str, reducer_fn: callable) tuple.
        Passing a bare callable will raise TypeError immediately at the first reducer call.
        """
        if target_map is None:
            target_map = {}

        grouped_rows: Dict[Any, list] = defaultdict(list)
        for row in rows:
            if not isinstance(row, dict):
                logging.warning("[Aggregator] Skipping non-dict row: %r", type(row))
                continue
            key = self.key_selector(row)
            if key is not None:
                grouped_rows[key].append(row)

        for key, group in grouped_rows.items():
            if key not in target_map:
                target_map[key] = {}

            for out_col, reducer_config in self.reducers.items():
                in_col, reducer_fn = reducer_config  # expects (str, callable) — see docstring
                existing_val = target_map[key].get(out_col)
                col_values = [row.get(in_col) for row in group if row.get(in_col) is not None]
                if existing_val is not None:
                    col_values.insert(0, existing_val)

                reduced_val = reducer_fn(col_values)
                if reduced_val is not None:
                    target_map[key][out_col] = reduced_val

        return target_map


def decimal_sum_reducer(values: List[Any], log_context: str = "") -> decimal.Decimal:
    """Sums values by converting them to decimal.Decimal."""
    total = decimal.Decimal(0)
    for val in values:
        if val is not None:
            if isinstance(val, decimal.Decimal):
                total += val
            else:
                dec_val = _convert_to_decimal(val, log_context)
                if dec_val is not None:
                    total += dec_val
    return total


def raw_cbm_reducer(values: List[Any]) -> Optional[str]:
    """Concatenates raw CBM values with ' + '."""
    cbm_list = []
    for val in values:
        if val:
            val_str = str(val).strip()
            if val_str:
                cbm_list.append(val_str)
    return " + ".join(cbm_list) if cbm_list else None


def raw_cbm_dedup_reducer(values: List[Any]) -> Optional[str]:
    """Concatenates raw CBM values with ' + ', avoiding duplicates."""
    cbm_list = []
    for val in values:
        if val:
            val_str = str(val).strip()
            if val_str:
                parts = [p.strip() for p in val_str.split(" + ")]
                for part in parts:
                    if part and part not in cbm_list:
                        cbm_list.append(part)
    return " + ".join(cbm_list) if cbm_list else None


def aggregate_standard_by_po_item_price(
    processed_data: List[Dict[str, Any]],
    global_aggregation_map: Dict[Tuple[Any, Any, Optional[decimal.Decimal], Optional[str]], Dict[str, decimal.Decimal]]
) -> Dict[Tuple[Any, Any, Optional[decimal.Decimal], Optional[str]], Dict[str, decimal.Decimal]]:
    """
    STANDARD Aggregation: Aggregates 'sqft' AND 'amount' values based on unique
    combinations of 'po', 'item', 'unit' price, AND 'description'.
    Updates the global_aggregation_map in place.
    """
    prefix = "[aggregate_standard]"
    required_cols = ['col_po', 'col_item', 'col_unit_price', 'col_qty_sf', 'col_amount']

    if not processed_data:
        logging.info(f"{prefix} No data rows found in this table. Global map unchanged.")
        return global_aggregation_map

    # Check for required columns existing in at least one row
    missing_cols = [col for col in required_cols if not any(col in row for row in processed_data)]
    if missing_cols:
        logging.warning(f"{prefix} Cannot perform STANDARD aggregation: Missing required columns {missing_cols}. Skipping this table.")
        return global_aggregation_map

    # Key selector
    def standard_key_selector(row):
        po_val, item_val = row.get('col_po'), row.get('col_item')
        unit_price_raw = row.get('col_unit_price')
        desc_raw = row.get('col_desc')
        
        po_key = str(po_val).strip() if isinstance(po_val, str) else po_val
        item_key = str(item_val).strip() if isinstance(item_val, str) else item_val
        description_key = str(desc_raw).strip() if isinstance(desc_raw, str) else desc_raw
        description_key = description_key if description_key else None

        po_key = po_key if po_key is not None else "<MISSING_PO>"
        item_key = item_key if item_key is not None else "<MISSING_ITEM>"

        price_dec = DataConverter.convert_to_decimal(unit_price_raw, "price")
        return (po_key, item_key, price_dec, description_key)

    # Reducers
    reducers = {
        'sqft_sum': ('col_qty_sf', lambda values: decimal_sum_reducer(values, "col_qty_sf")),
        'amount_sum': ('col_amount', lambda values: decimal_sum_reducer(values, "col_amount")),
        'net_sum': ('col_net', lambda values: decimal_sum_reducer(values, "col_net")),
        'col_cbm_raw': ('col_cbm_raw', raw_cbm_reducer)
    }

    # Run Aggregator
    aggregator = Aggregator(key_selector=standard_key_selector, reducers=reducers)
    aggregator.aggregate(processed_data, global_aggregation_map)

    logging.info(f"{prefix} Finished processing rows.")
    return global_aggregation_map


def aggregate_custom_by_po_item(
    processed_data: List[Dict[str, Any]],
    global_custom_aggregation_map: Dict[Tuple[Any, Any, None, Optional[str]], Dict[str, decimal.Decimal]]
) -> Dict[Tuple[Any, Any, None, Optional[str]], Dict[str, decimal.Decimal]]:
    """
    CUSTOM Aggregation: Aggregates 'sqft' and 'amount' values based on unique
    combinations of 'po', 'item', AND 'description'. Uses a 4-element key
    (PO, Item, None, Description) for structural consistency with standard aggregation.
    Updates the global_custom_aggregation_map in place.
    """
    prefix = "[aggregate_custom]"
    required_cols = ['col_po', 'col_item', 'col_qty_sf', 'col_amount']

    if not processed_data:
        logging.info(f"{prefix} No data rows found in this table. Global custom aggregation map remains unchanged.")
        return global_custom_aggregation_map

    # Check for required columns existing in at least one row
    missing_cols = [col for col in required_cols if not any(col in row for row in processed_data)]
    if missing_cols:
        logging.warning(f"{prefix} Cannot perform full CUSTOM aggregation: Missing required columns {missing_cols}. Proceeding cautiously.")

    # Key selector
    def custom_key_selector(row):
        po_val, item_val = row.get('col_po'), row.get('col_item')
        desc_raw = row.get('col_desc')
        
        po_key = str(po_val).strip() if isinstance(po_val, str) else po_val
        item_key = str(item_val).strip() if isinstance(item_val, str) else item_val
        description_key = str(desc_raw).strip() if isinstance(desc_raw, str) else desc_raw
        description_key = description_key if description_key else None

        po_key = po_key if po_key is not None else "<MISSING_PO>"
        item_key = item_key if item_key is not None else "<MISSING_ITEM>"

        return (po_key, item_key, None, description_key)

    # Reducers
    reducers = {
        'sqft_sum': ('col_qty_sf', lambda values: decimal_sum_reducer(values, "col_qty_sf")),
        'amount_sum': ('col_amount', lambda values: decimal_sum_reducer(values, "col_amount")),
        'net_sum': ('col_net', lambda values: decimal_sum_reducer(values, "col_net")),
        'col_cbm_raw': ('col_cbm_raw', raw_cbm_reducer)
    }

    # Run Aggregator
    aggregator = Aggregator(key_selector=custom_key_selector, reducers=reducers)
    aggregator.aggregate(processed_data, global_custom_aggregation_map)

    logging.info(f"{prefix} Finished processing rows.")
    return global_custom_aggregation_map


def calculate_leather_summary(processed_data: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Calculates the leather summary (PCS, SQFT, Net, Gross, Pallet Count) per leather type.
    Iterates through rows to sum values for each leather type found in 'description' or 'desc'.
    BUFFALO = rows containing "BUFFALO" in description
    COW = rows NOT containing "BUFFALO" (all other leather)
    """
    summary = {
        'BUFFALO': {'col_qty_pcs': 0, 'col_qty_sf': decimal.Decimal(0), 'col_net': decimal.Decimal(0), 'col_gross': decimal.Decimal(0), 'col_cbm': decimal.Decimal(0), 'col_pallet_count': 0},
        'COW': {'col_qty_pcs': 0, 'col_qty_sf': decimal.Decimal(0), 'col_net': decimal.Decimal(0), 'col_gross': decimal.Decimal(0), 'col_cbm': decimal.Decimal(0), 'col_pallet_count': 0}
    }

    if not processed_data:
        return summary

    def leather_type_key_selector(row):
        desc = str(row.get('col_desc', "")).upper() if row.get('col_desc') else ""
        return 'BUFFALO' if "BUFFALO" in desc else 'COW'

    def int_sum_reducer(values: List[Any]) -> int:
        total = 0
        for val in values:
            if val is not None:
                try:
                    total += int(float(str(val)))
                except (ValueError, TypeError):
                    pass
        return total

    reducers = {
        'col_qty_pcs': ('col_qty_pcs', _int_sum_reducer),
        'col_qty_sf': ('col_qty_sf', lambda values: decimal_sum_reducer(values, "leather sqft")),
        'col_net': ('col_net', lambda values: decimal_sum_reducer(values, "leather net")),
        'col_gross': ('col_gross', lambda values: decimal_sum_reducer(values, "leather gross")),
        'col_cbm': ('col_cbm', lambda values: decimal_sum_reducer(values, "leather cbm")),
        'col_pallet_count': ('col_pallet_count', _int_sum_reducer),
    }

    aggregator = Aggregator(key_selector=leather_type_key_selector, reducers=reducers)
    aggregator.aggregate(processed_data, summary)
    return summary


def aggregate_per_po_with_pallets(processed_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Aggregates data by PO and Item, summing pallet, pcs, sqft, amount, net, gross, cbm.
    Groups rows that share the same (PO, Item) combination.
    """
    if not isinstance(processed_data, list) or not processed_data:
        return []

    # Key selector
    def po_item_key_selector(row):
        po_val = row.get('col_po')
        if po_val is None:
            return None
        po = str(po_val).strip()
        if not po:
            return None
        item_val = row.get('col_item')
        item = str(item_val).strip() if item_val is not None else ""
        return (po, item)

    # Reducers
    def first_non_empty_reducer(values: List[Any]) -> str:
        for val in values:
            if val:
                val_str = str(val).strip()
                if val_str:
                    return val_str
        return ""


    reducers = {
        'col_desc': ('col_desc', first_non_empty_reducer),
        'col_qty_pcs': ('col_qty_pcs', _int_sum_reducer),
        'col_qty_sf': ('col_qty_sf', lambda values: decimal_sum_reducer(values, "sqft")),
        'col_amount': ('col_amount', lambda values: decimal_sum_reducer(values, "amount")),
        'col_pallet_count': ('col_pallet_count', _int_sum_reducer),
        'col_net': ('col_net', lambda values: decimal_sum_reducer(values, "net")),
        'col_gross': ('col_gross', lambda values: decimal_sum_reducer(values, "gross")),
        'col_cbm': ('col_cbm', lambda values: decimal_sum_reducer(values, "cbm")),
        'col_cbm_raw': ('col_cbm_raw', raw_cbm_dedup_reducer)
    }

    # Aggregate using Aggregator
    aggregator = Aggregator(key_selector=po_item_key_selector, reducers=reducers)
    agg_map = aggregator.aggregate(processed_data)

    # Convert to list of dicts
    result = []
    for (po, item), data in agg_map.items():
        result.append({
            'col_po': po,
            'col_item': item,
            'col_desc': data.get('col_desc', ''),
            'col_qty_pcs': data.get('col_qty_pcs', 0),
            'col_qty_sf': data.get('col_qty_sf', decimal.Decimal(0)),
            'col_amount': data.get('col_amount', decimal.Decimal(0)),
            'col_pallet_count': data.get('col_pallet_count', 0),
            'col_net': data.get('col_net', decimal.Decimal(0)),
            'col_gross': data.get('col_gross', decimal.Decimal(0)),
            'col_cbm': data.get('col_cbm', decimal.Decimal(0)),
            'col_cbm_raw': data.get('col_cbm_raw', '') or ''
        })

    # Sort by PO, then by Item for consistent output
    result.sort(key=lambda x: (x['col_po'], x['col_item']))
    
    logging.info(f"[aggregate_per_po_with_pallets] Aggregated {len(processed_data)} rows into {len(result)} unique PO+Item combinations.")
    return result


def calculate_weight_summary(processed_data: List[Dict[str, Any]]) -> Dict[str, decimal.Decimal]:
    """Calculates the weight summary (Net Weight and Gross Weight)."""
    summary = {'col_net': decimal.Decimal(0), 'col_gross': decimal.Decimal(0)}
    if not processed_data:
        return summary
        
    summary['col_net'] = decimal_sum_reducer([r.get('col_net') for r in processed_data], "weight summary net")
    summary['col_gross'] = decimal_sum_reducer([r.get('col_gross') for r in processed_data], "weight summary gross")
    return summary


def calculate_pallet_summary(processed_data: List[Dict[str, Any]]) -> int:
    """Calculates the total pallet count for the table."""
    total_pallets = 0
    if not processed_data:
        return 0
        
    for row in processed_data:
        val = row.get('col_pallet_count')
        if val is not None:
            try:
                total_pallets += int(float(str(val)))
            except (ValueError, TypeError):
                pass
    return total_pallets


def calculate_footer_totals(processed_data: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Calculates totals for footer fields based on processed data."""
    totals = {
        "col_qty_pcs": 0,
        "col_qty_sf": decimal.Decimal(0),
        "col_net": decimal.Decimal(0),
        "col_gross": decimal.Decimal(0),
        "col_cbm": decimal.Decimal(0),
        "col_amount": decimal.Decimal(0),
        "col_pallet_count": 0
    }
    
    if not processed_data:
        return totals


    def dec_sum_reducer(values: List[Any]) -> decimal.Decimal:
        total = decimal.Decimal(0)
        for val in values:
            if val is not None:
                try:
                    val_str = str(val).replace(',', '')
                    total += decimal.Decimal(val_str)
                except (decimal.InvalidOperation, ValueError, TypeError):
                    pass
        return total

    totals['col_qty_pcs'] = _int_sum_reducer([r.get('col_qty_pcs') for r in processed_data])
    totals['col_qty_sf'] = dec_sum_reducer([r.get('col_qty_sf') for r in processed_data])
    totals['col_net'] = dec_sum_reducer([r.get('col_net') for r in processed_data])
    totals['col_gross'] = dec_sum_reducer([r.get('col_gross') for r in processed_data])
    totals['col_cbm'] = dec_sum_reducer([r.get('col_cbm') for r in processed_data])
    totals['col_amount'] = dec_sum_reducer([r.get('col_amount') for r in processed_data])
    totals['col_pallet_count'] = _int_sum_reducer([r.get('col_pallet_count') for r in processed_data])

    return totals


def format_aggregation_as_list(
    aggregation_map: Dict[Tuple, Dict[str, decimal.Decimal]],
    mode: str = 'standard'
) -> List[Dict[str, Any]]:
    """
    Converts the internal tuple-keyed aggregation map into a clean list of dictionaries
    suitable for JSON output. Removes tuple keys and uses 'col_' prefixed keys for all fields.
    """
    flattened_list = []
    
    for key_tuple, values in aggregation_map.items():
        row_dict = {}
        
        # Extract values from the tuple key based on mode
        if mode == 'standard':
            if len(key_tuple) >= 4:
                row_dict['col_po'] = str(key_tuple[0]) if key_tuple[0] is not None else ""
                row_dict['col_item'] = str(key_tuple[1]) if key_tuple[1] is not None else ""
                row_dict['col_unit_price'] = str(key_tuple[2]) if key_tuple[2] is not None else ""
                row_dict['col_desc'] = str(key_tuple[3]) if key_tuple[3] is not None else ""
            else:
                row_dict['col_po'] = str(key_tuple[0]) if len(key_tuple) > 0 else ""
                row_dict['col_item'] = str(key_tuple[1]) if len(key_tuple) > 1 else ""
                
        elif mode == 'custom':
            if len(key_tuple) >= 4:
                row_dict['col_po'] = str(key_tuple[0]) if key_tuple[0] is not None else ""
                row_dict['col_item'] = str(key_tuple[1]) if key_tuple[1] is not None else ""
                row_dict['col_desc'] = str(key_tuple[3]) if key_tuple[3] is not None else ""
            else:
                row_dict['col_po'] = str(key_tuple[0]) if len(key_tuple) > 0 else ""
                row_dict['col_item'] = str(key_tuple[1]) if len(key_tuple) > 1 else ""

        sqft_sum = values.get('sqft_sum', decimal.Decimal(0))
        amount_sum = values.get('amount_sum', decimal.Decimal(0))
        net_sum = values.get('net_sum', decimal.Decimal(0))
        
        row_dict['col_qty_sf'] = float(sqft_sum) if isinstance(sqft_sum, decimal.Decimal) else sqft_sum
        row_dict['col_amount'] = float(amount_sum) if isinstance(amount_sum, decimal.Decimal) else amount_sum
        row_dict['col_net'] = float(net_sum) if isinstance(net_sum, decimal.Decimal) else net_sum
        
        if 'col_cbm_raw' in values:
            row_dict['col_cbm_raw'] = values['col_cbm_raw']
            
        flattened_list.append(row_dict)
        
    return flattened_list
