"""initial_schema

Revision ID: 20a9bb8ceb01
Revises: 
Create Date: 2026-08-05 14:42:43.913124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a9bb8ceb01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'source_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('source_file', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
