import logging
from collections import defaultdict
from typing import List, Dict, Any, Tuple, Optional


class Aggregator:
    """
    Generic, declarative data aggregator that groups rows by a key generated by
    key_selector and applies column-specific reduction strategies.
    """
    def __init__(self, key_selector, reducers):
        self.key_selector = key_selector
        self.reducers = reducers

    def aggregate(self, rows: List[Dict[str, Any]], target_map: Dict[Tuple, Dict[str, Any]] = None) -> Dict[Tuple, Dict[str, Any]]:
        """
        Reduce rows into target_map.

        Each entry in self.reducers must be a (in_col: str, reducer_fn: callable) tuple.
        Passing a bare callable will raise TypeError immediately at the first reducer call.
        """
        if target_map is None:
            target_map = {}

        grouped_rows: Dict[Any, list] = defaultdict(list)
        for row in rows:
            if not isinstance(row, dict):
                logging.warning("[Aggregator] Skipping non-dict row: %r", type(row))
                continue
            key = self.key_selector(row)
            if key is not None:
                grouped_rows[key].append(row)

        for key, group in grouped_rows.items():
            if key not in target_map:
                target_map[key] = {}

            for out_col, reducer_config in self.reducers.items():
                in_col, reducer_fn = reducer_config  # expects (str, callable) — see docstring
                existing_val = target_map[key].get(out_col)
                col_values = [row.get(in_col) for row in group if row.get(in_col) is not None]
                if existing_val is not None:
                    col_values.insert(0, existing_val)

                reduced_val = reducer_fn(col_values)
                if reduced_val is not None:
                    target_map[key][out_col] = reduced_val

        return target_map
